version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5673"
      - "15673:15673"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
